export const projectsData = [
	{
		id: 1,
		name: 'What if',
		description: 'Demonstração dos personagens marvel em nextJs',
		date: '10-10-2023',
		demoLink: 'https://devjamas-whatif.vercel.app/',
	},
	{
		id: 2,
		name: 'NFTBoost',
		description: 'Site de NFT com alguns exemplares em NextJs e Tailwind',
		date: '12-23-2023',
		demoLink: 'https://nft-boost-ruddy.vercel.app/',
	},
	{
		id: 3,
		name: 'IMDb',
		description: 'Clone do site IMDb - Filmes',
		date: '02-02-2024',
		demoLink: 'https://imdb-next-mu.vercel.app/',
	},
	{
		id: 4,
		name: 'Fokus',
		description: 'Timer para foco',
		date: '09-10-2023',
		demoLink: 'https://fokus-by-ismael.netlify.app/',
	},
	{
		id: 5,
		name: 'Pokemon',
		description: 'Pokedex',
		date: '09-10-2023',
		demoLink: 'https://pokemon-by-ismael.netlify.app/',
	},
	{
		id: 6,
		name: 'MoniBank',
		description: 'Exemplo de serviço para abrir conta',
		date: '10-20-2023',
		demoLink: 'https://monibank-ismael.netlify.app/',
	},
	{
		id: 7,
		name: 'Dev&Dragons',
		description: 'Duelo de cartas',
		date: '10-01-2023',
		demoLink: 'https://ded-devs-ismael.netlify.app/',
	},
	{
		id: 8,
		name: 'Blizzard',
		description: 'Demo de um possível site da blizzard',
		date: '11-30-2022',
		demoLink: 'https://project-blizzard-codeboost.netlify.app/',
	},
	{
		id: 9,
		name: 'Dk trainers',
		description: 'Projeto desenvolvido para Abordo',
		date: '11-30-2022',
		demoLink: 'https://projectdktrainers.netlify.app/',
	},
	{
		id: 10,
		name: 'Dunia',
		description: 'Projeto desenvolvido para Abordo',
		date: '12-31-2022',
		demoLink: 'https://stunning-griffin-515115.netlify.app/',
	},
	{
		id: 11,
		name: 'Flppy Bird',
		description: 'Jogo Flappy Bird Web',
		date: '12-6-2022',
		demoLink: 'https://flappybird-integracao-js.netlify.app/',
	},
];

export const BtnList = [
	{ label: 'Sobre', link: '/about', icon: 'about', newTab: false },
	{ label: 'Projetos', link: '/projects', icon: 'projects', newTab: false },
	{ label: 'Contato', link: '/contact', icon: 'contact', newTab: false },
	{
		label: 'Github',
		link: 'https://www.github.com/ismaelp96',
		icon: 'github',
		newTab: true,
	},
	{
		label: 'LinkedIn',
		link: 'https://www.linkedin.com/in/ismael-oliveira-5b4a98135/',
		icon: 'linkedin',
		newTab: true,
	},
	{
		label: 'Instagram',
		link: 'https://instagram.com/ismaelp96',
		icon: 'instagram',
		newTab: true,
	},
];
