import { Inter } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';
import FireFlisBackground from '@/components/FireFliesBackground';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata = {
  title: 'Portifolio 3D',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='pt-BR'>
      <body className={clsx(inter.variable, 'bg-background text-foreground')}>
        {children}
        <FireFlisBackground />
      </body>
    </html>
  );
}
